parameters:
#    ecommerce.example.class: Ecommerce\EcommerceBundle\Example

services:
#    ecommerce.example:
#        class: %ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    setNewFacture:
        class: Ecommerce\EcommerceBundle\Service\getFacture
        arguments: [@service_container]

    setNewReference:
        class: Ecommerce\EcommerceBundle\Service\getReference
        arguments: [@security.context, @doctrine.orm.entity_manager]
    
    tva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
        tags: 
          - { name: twig.extension }
          
    montantTva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\MontantTvaExtension
        tags: 
          - { name: twig.extension }
        
#    redirectionListener:
#        class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
#       arguments: [@service_container,@session]
#        tags:
#         - { name: kernel.event_listener, event: kernel.request, method: onkernelRequest }