adminCategories:
    path:     /
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:index" }

adminCategories_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:show" }

adminCategories_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:new" }

adminCategories_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:create" }
    methods:  POST

adminCategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:edit" }

adminCategories_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:update" }
    methods:  [POST, PUT]

adminCategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:categoriesAdmin:delete" }
    methods:  [POST, DELETE]
