adminCommandes:
    path:     /
    defaults: { _controller: "EcommerceBundle:commandesAdmin:index" }

adminCommandes_show:
    path:     /
    defaults: { _controller: "EcommerceBundle:commandesAdmin:showFacture" }
