<?php

namespace Pages\PagesBundle\Entity;

/**
 * pagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pagesRepository extends \Doctrine\ORM\EntityRepository
{
}
