# app/config/routing.yml
routingUtilisateursAdmin:
    resource: "@UtilisateursBundle/Resources/config/routing/routingUtilisateursAdmin.yml"
    prefix:   /admin/utilisateurs
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
   
factures:
    path: /profile/facture
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures}
    
facturesPDF:
    path: /profile/facture/pdf/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturesPDF}

villes:
    path: /villes/{cp}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:villes}
    
